using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using StokTakip.Application.Common;
using StokTakip.Domain.Common;
using StokTakip.Domain.Entities;
using StokTakip.Infrastructure.Data.Configurations;
using StokTakip.Infrastructure.Identity;

namespace StokTakip.Infrastructure.Data;

public class AppDbContext : IdentityDbContext<ApplicationUser>, IAppDbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Supplier> Suppliers => Set<Supplier>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<StockMovement> StockMovements => Set<StockMovement>();
    public DbSet<Notification> Notifications => Set<Notification>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        // unaccent supplies the folding table (a maintained dictionary rather than a hand-kept
        // list of Turkish pairs); pg_trgm is what makes an unanchored LIKE indexable.
        builder.HasPostgresExtension("unaccent");
        builder.HasPostgresExtension("pg_trgm");

        // SearchText.Fold has no body in C# — this mapping is what gives it one. The searched
        // columns are generated by the same f_fold(), so term and column are folded by identical
        // code and cannot drift.
        builder.HasDbFunction(typeof(SearchText).GetMethod(nameof(SearchText.Fold), [typeof(string)])!)
            .HasName(PostgresText.FoldFunction);
    }

    public override int SaveChanges()
    {
        ApplyAudit();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ApplyAudit();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void ApplyAudit()
    {
        // One timestamp for the whole SaveChanges: rows written together carry the same instant,
        // so an ordering can never be read into what is actually a single transaction.
        var now = DateTime.UtcNow;
        foreach (var entry in ChangeTracker.Entries())
            ApplyAuditTo(entry, now);
    }

    private static void ApplyAuditTo(EntityEntry entry, DateTime now)
    {
        if (entry.State == EntityState.Added && entry.Entity is IHasCreatedAt created)
            created.CreatedAt = now;

        if (entry.State == EntityState.Added && entry.Entity is IAuditable addedAuditable)
            addedAuditable.UpdatedAt = now;

        if (entry.State == EntityState.Modified && entry.Entity is IAuditable modifiedAuditable)
            modifiedAuditable.UpdatedAt = now;

        // "Since when is this out of use" is one question, so it gets one answer, written
        // here instead of by each service that happens to flip the flag. Only a real
        // transition writes: an edit that leaves IsActive alone must not move the date,
        // which is why the property — not the entity — is asked whether it changed.
        if (entry.Entity is IDeactivatable deactivatable && ChangedActivity(entry))
            deactivatable.DeactivatedAt = deactivatable.IsActive ? null : now;
    }

    private static bool ChangedActivity(EntityEntry entry) => entry.State switch
    {
        // A row can also be born passive; it deserves the same stamp as one that was switched off.
        EntityState.Added => !((IDeactivatable)entry.Entity).IsActive,
        EntityState.Modified => entry.Property(nameof(IDeactivatable.IsActive)).IsModified,
        _ => false
    };
}
