using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using StokTakip.Application.Common;
using StokTakip.Domain.Common;
using StokTakip.Domain.Entities;
using StokTakip.Infrastructure.Data.Configurations;
using StokTakip.Infrastructure.Identity;

namespace StokTakip.Infrastructure.Data;

public class AppDbContext : IdentityDbContext<ApplicationUser>, IAppDbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Supplier> Suppliers => Set<Supplier>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<StockMovement> StockMovements => Set<StockMovement>();
    public DbSet<Notification> Notifications => Set<Notification>();

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        // unaccent supplies the folding table (a maintained dictionary rather than a hand-kept
        // list of Turkish pairs); pg_trgm is what makes an unanchored LIKE indexable.
        builder.HasPostgresExtension("unaccent");
        builder.HasPostgresExtension("pg_trgm");

        // SearchText.Fold has no body in C# — this mapping is what gives it one. The searched
        // columns are generated by the same f_fold(), so term and column are folded by identical
        // code and cannot drift.
        builder.HasDbFunction(typeof(SearchText).GetMethod(nameof(SearchText.Fold), [typeof(string)])!)
            .HasName(PostgresText.FoldFunction);
    }

    public override int SaveChanges()
    {
        ApplyAudit();
        return base.SaveChanges();
    }

    public override Task<int> SaveChangesAsync(CancellationToken cancellationToken = default)
    {
        ApplyAudit();
        return base.SaveChangesAsync(cancellationToken);
    }

    private void ApplyAudit()
    {
        var now = DateTime.UtcNow;
        foreach (var entry in ChangeTracker.Entries())
        {
            if (entry.State == EntityState.Added && entry.Entity is IHasCreatedAt created)
                created.CreatedAt = now;

            if (entry.State == EntityState.Added && entry.Entity is IAuditable addedAuditable)
                addedAuditable.UpdatedAt = now;

            if (entry.State == EntityState.Modified && entry.Entity is IAuditable modifiedAuditable)
                modifiedAuditable.UpdatedAt = now;
        }
    }
}
