using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StokTakip.Application.Common;
using StokTakip.Domain.Entities;

namespace StokTakip.Infrastructure.Data.Configurations;

public class CategoryConfiguration : IEntityTypeConfiguration<Category>
{
    public void Configure(EntityTypeBuilder<Category> builder)
    {
        builder.Property(c => c.Id).UseIdentityAlwaysColumn();
        builder.Property(c => c.Name).HasMaxLength(100).IsRequired()
            .UseCollation(PostgresText.TurkishCollation);
        builder.Property(c => c.Description).HasMaxLength(500);
        builder.Property(c => c.IsActive).HasDefaultValue(true);

        // Uniqueness on the Turkish lower-case name, not on the name as typed (D9c): GIDA = Gıda,
        // Kıl ≠ Kil. Generated by the database from the same f_name_key() the service's pre-check
        // calls, so the two cannot disagree on what "the same name" is.
        builder.Property<string>(NameText.NameKey)
            .HasMaxLength(100)
            .HasComputedColumnSql(PostgresText.Keyed("Name"), stored: true);

        builder.HasIndex(NameText.NameKey).IsUnique().HasDatabaseName("UQ_Categories_NameKey");

        // Product search also matches on the category name, so it needs the same search key.
        // See ProductConfiguration for why the database generates it.
        builder.Property<string>(SearchText.NameFolded)
            .HasMaxLength(100)
            .HasComputedColumnSql(PostgresText.Folded("Name"), stored: true);

        builder.HasIndex(SearchText.NameFolded)
            .HasDatabaseName("IX_Categories_NameFolded")
            .HasMethod("gin")
            .HasOperators(PostgresText.TrigramOperators);
    }
}
