using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StokTakip.Application.Common;
using StokTakip.Domain.Entities;

namespace StokTakip.Infrastructure.Data.Configurations;

public class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.Property(p => p.Id).UseIdentityAlwaysColumn();
        builder.Property(p => p.Name).HasMaxLength(150).IsRequired()
            .UseCollation(PostgresText.TurkishCollation);
        builder.Property(p => p.SKU).HasMaxLength(30).IsRequired();
        builder.Property(p => p.Description).HasMaxLength(500);
        builder.Property(p => p.UnitPrice).HasPrecision(18, 2);
        builder.Property(p => p.StockQuantity).HasDefaultValue(0);
        builder.Property(p => p.MinStockLevel).HasDefaultValue(5);
        builder.Property(p => p.IsActive).HasDefaultValue(true);

        builder.HasIndex(p => p.SKU).IsUnique().HasDatabaseName("UQ_Products_SKU");

        // Search keys. Generated by the database rather than by the application, so every row
        // carries one no matter how it got there — seed, migration, or a hand-written INSERT —
        // and the value cannot drift from the term the query folds, because both go through
        // f_fold(). Shadow properties: this is a persistence concern and the Domain entity stays
        // a plain POCO.
        builder.Property<string>(SearchText.NameFolded)
            .HasMaxLength(150)
            .HasComputedColumnSql(PostgresText.Folded("Name"), stored: true);

        builder.Property<string>(SearchText.SkuFolded)
            .HasMaxLength(30)
            .HasComputedColumnSql(PostgresText.Folded("SKU"), stored: true);

        builder.HasIndex(SearchText.NameFolded)
            .HasDatabaseName("IX_Products_NameFolded")
            .HasMethod("gin")
            .HasOperators(PostgresText.TrigramOperators);

        builder.HasIndex(SearchText.SkuFolded)
            .HasDatabaseName("IX_Products_SkuFolded")
            .HasMethod("gin")
            .HasOperators(PostgresText.TrigramOperators);

        // Optimistic concurrency via PostgreSQL's system column "xmin": a uint concurrency
        // token that Postgres itself bumps on every UPDATE. The Npgsql convention maps this
        // shadow property onto the system column, so the migration creates no real column.
        builder.Property<uint>("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        builder.HasOne(p => p.Category)
            .WithMany(c => c.Products)
            .HasForeignKey(p => p.CategoryId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(p => p.Supplier)
            .WithMany(s => s.Products)
            .HasForeignKey(p => p.SupplierId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.ToTable(t =>
        {
            t.HasCheckConstraint("CK_Products_UnitPrice", "\"UnitPrice\" >= 0");
            t.HasCheckConstraint("CK_Products_StockQuantity", "\"StockQuantity\" >= 0");
            t.HasCheckConstraint("CK_Products_MinStockLevel", "\"MinStockLevel\" >= 0");
        });
    }
}
