using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using StokTakip.Application.Common;
using StokTakip.Domain.Entities;

namespace StokTakip.Infrastructure.Data.Configurations;

public class ProductConfiguration : IEntityTypeConfiguration<Product>
{
    public void Configure(EntityTypeBuilder<Product> builder)
    {
        builder.Property(p => p.Id).UseIdentityAlwaysColumn();
        builder.Property(p => p.Name).HasMaxLength(150).IsRequired()
            .UseCollation(PostgresText.TurkishCollation);
        builder.Property(p => p.SKU).HasMaxLength(30).IsRequired();
        builder.Property(p => p.Description).HasMaxLength(500);
        builder.Property(p => p.UnitPrice).HasPrecision(18, 2);
        builder.Property(p => p.StockQuantity).HasDefaultValue(0);
        // A store default makes EF treat one value as "not set" and leave the column out of the
        // INSERT. For int that value is 0 — a legitimate threshold, which silently became 5. Any
        // other sentinel only moves the hole (a -1 would turn into 5 instead of hitting
        // CK_Products_MinStockLevel), so EF is told to always send what the entity holds; the
        // schema's default still serves raw INSERTs.
        builder.Property(p => p.MinStockLevel).HasDefaultValue(5).ValueGeneratedNever();
        builder.Property(p => p.IsActive).HasDefaultValue(true);

        builder.HasIndex(p => p.SKU).IsUnique().HasDatabaseName("UQ_Products_SKU");

        // Search keys. Generated by the database rather than by the application, so every row
        // carries one no matter how it got there — seed, migration, or a hand-written INSERT —
        // and the value cannot drift from the term the query folds, because both go through
        // f_fold(). Shadow properties: this is a persistence concern and the Domain entity stays
        // a plain POCO.
        builder.Property<string>(SearchText.NameFolded)
            .HasMaxLength(150)
            .HasComputedColumnSql(PostgresText.Folded("Name"), stored: true);

        builder.Property<string>(SearchText.SkuFolded)
            .HasMaxLength(30)
            .HasComputedColumnSql(PostgresText.Folded("SKU"), stored: true);

        builder.HasIndex(SearchText.NameFolded)
            .HasDatabaseName("IX_Products_NameFolded")
            .HasMethod("gin")
            .HasOperators(PostgresText.TrigramOperators);

        builder.HasIndex(SearchText.SkuFolded)
            .HasDatabaseName("IX_Products_SkuFolded")
            .HasMethod("gin")
            .HasOperators(PostgresText.TrigramOperators);

        // Optimistic concurrency via PostgreSQL's system column "xmin": a uint concurrency
        // token that Postgres itself bumps on every UPDATE. Mapped onto the entity's own
        // RowVersion property (the form the Npgsql documentation shows) rather than a shadow
        // property, so projections read p.RowVersion instead of EF.Property<uint>(p, "xmin").
        // The column name is what keeps the migration from creating a real column — Npgsql
        // recognises "xmin" as a system column.
        builder.Property(p => p.RowVersion)
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .ValueGeneratedOnAddOrUpdate()
            .IsConcurrencyToken();

        builder.HasOne(p => p.Category)
            .WithMany(c => c.Products)
            .HasForeignKey(p => p.CategoryId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasOne(p => p.Supplier)
            .WithMany(s => s.Products)
            .HasForeignKey(p => p.SupplierId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.ToTable(t =>
        {
            t.HasCheckConstraint("CK_Products_UnitPrice", "\"UnitPrice\" >= 0");
            t.HasCheckConstraint("CK_Products_StockQuantity", "\"StockQuantity\" >= 0");
            t.HasCheckConstraint("CK_Products_MinStockLevel", "\"MinStockLevel\" >= 0");

            // D8: the stored SKU — trimmed and upper-cased by the service — is ASCII letters,
            // digits and . _ / - only. A regex, not upper(): upper() depends on the database's
            // ctype and gave different answers in dev and in the container (see SkuRule).
            t.HasCheckConstraint("CK_Products_SKU", "\"SKU\" ~ '^[A-Z0-9._/-]+$'");
        });
    }
}
